//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.etsoo.CMS.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.etsoo.CMS.Server.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change self password.
        /// </summary>
        internal static string ChangeSelfPassword {
            get {
                return ResourceManager.GetString("ChangeSelfPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create article {0}.
        /// </summary>
        internal static string CreateArticle {
            get {
                return ResourceManager.GetString("CreateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or update resource {0}.
        /// </summary>
        internal static string CreateResource {
            get {
                return ResourceManager.GetString("CreateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create service {0}.
        /// </summary>
        internal static string CreateService {
            get {
                return ResourceManager.GetString("CreateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tab {0}.
        /// </summary>
        internal static string CreateTab {
            get {
                return ResourceManager.GetString("CreateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user {0}.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Website Settings.
        /// </summary>
        internal static string CreateWebsiteSettings {
            get {
                return ResourceManager.GetString("CreateWebsiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete article {0}.
        /// </summary>
        internal static string DeleteArticle {
            get {
                return ResourceManager.GetString("DeleteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete article {0} photo.
        /// </summary>
        internal static string DeleteArticlePhoto {
            get {
                return ResourceManager.GetString("DeleteArticlePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file {0}.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tab {0}.
        /// </summary>
        internal static string DeleteTab {
            get {
                return ResourceManager.GetString("DeleteTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user {0}.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in successfully.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset user {0} password.
        /// </summary>
        internal static string ResetUserPassword {
            get {
                return ResourceManager.GetString("ResetUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share file {0}.
        /// </summary>
        internal static string ShareFile {
            get {
                return ResourceManager.GetString("ShareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort article {0} photos.
        /// </summary>
        internal static string SortArticlePhotos {
            get {
                return ResourceManager.GetString("SortArticlePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token login.
        /// </summary>
        internal static string TokenLogin {
            get {
                return ResourceManager.GetString("TokenLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update article {0}.
        /// </summary>
        internal static string UpdateArticle {
            get {
                return ResourceManager.GetString("UpdateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update article {0} gallery.
        /// </summary>
        internal static string UpdateArticleGallery {
            get {
                return ResourceManager.GetString("UpdateArticleGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save photo file {0}.
        /// </summary>
        internal static string UpdateArticleGalleryError {
            get {
                return ResourceManager.GetString("UpdateArticleGalleryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update article {0} gallery photo item.
        /// </summary>
        internal static string UpdateArticleGalleryItem {
            get {
                return ResourceManager.GetString("UpdateArticleGalleryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update article {0} logo.
        /// </summary>
        internal static string UpdateArticleLogo {
            get {
                return ResourceManager.GetString("UpdateArticleLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file {0}.
        /// </summary>
        internal static string UpdateFile {
            get {
                return ResourceManager.GetString("UpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update website resource URL.
        /// </summary>
        internal static string UpdateResourceUrl {
            get {
                return ResourceManager.GetString("UpdateResourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update service {0}.
        /// </summary>
        internal static string UpdateService {
            get {
                return ResourceManager.GetString("UpdateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update tab {0}.
        /// </summary>
        internal static string UpdateTab {
            get {
                return ResourceManager.GetString("UpdateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update tab {0} logo.
        /// </summary>
        internal static string UpdateTabLogo {
            get {
                return ResourceManager.GetString("UpdateTabLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user {0}.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Website Settings.
        /// </summary>
        internal static string UpdateWebsiteSettings {
            get {
                return ResourceManager.GetString("UpdateWebsiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file {0}.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extension found for file {0}.
        /// </summary>
        internal static string UploadFileError {
            get {
                return ResourceManager.GetString("UploadFileError", resourceCulture);
            }
        }
    }
}
